persistence:
  enabled: false

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  uptime.conf: |
    input { exec { command => "uptime" interval => 30 } }
    output {
      elasticsearch {
        hosts => ["https://${ELASTICSEARCH_HOST}:9200"]
        user => '${ELASTICSEARCH_USERNAME}'
        password => '${ELASTICSEARCH_PASSWORD}'
        index => "logstash"
      }
    }

extraEnvs:
  - name: "ELASTICSEARCH_USERNAME"
    valueFrom:
      configMapKeyRef:
        name: my-secret
        key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      configMapKeyRef:
        name: my-secret
        key: password
  - name: "ELASTICSEARCH_HOST"
    valueFrom:
      configMapKeyRef:
        name: my-secret
        key: host

# secretMounts:
#   - name: elasticsearch-master-certs
#     secretName: elasticsearch-master-certs
#     path: /usr/share/logstash/config/certs