apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook2
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - logstash2
      - logstash3
  template:
    metadata:
      name: '{{.}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: 'git@github.com:emelianrus/argocd_testing.git'
        path: apps/in-cluster/base-chart
        helm:
          valueFiles:
            - apps/in-cluster/{{.}}/helm/values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: app