apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook2
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
        - repoURL: git@github.com:emelianrus/argocd_testing.git
          targetRevision: master
          files:
          - path: list-elementsYaml-example.yaml
      - list:
          elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: '{{.name}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: 'git@github.com:emelianrus/argocd_testing.git'
        path: apps/in-cluster/{{.name}}/helm/values.yaml
        helm:
          valueFiles:
            - apps/in-cluster/{{.name}}/helm/values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: app