apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appgenerator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: 'git@github.com:emelianrus/argocd_testing.git'
          revision: master
          files:
          - path: apps/in-cluster/test/list-elementsYaml-example.yaml
      - list:
          elementsYaml: "{{ .apps | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
      labels:
        variableA: '{{.variable1}}'
    spec:
      project: "default"
      sources:
        - repoURL: 'git@github.com:emelianrus/argocd_testing.git'
          path: apps/in-cluster/test/base-chart
          chart: base-chart
          targetRevision: 'master'
          helm:
            valueFiles:
              - /apps/in-cluster/{{.name}}/helm/values.yaml
        - repoURL: 'git@github.com:emelianrus/argocd_testing.git'
          targetRevision: 'master'
          ref: values

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: app
      info:
      - name: 'Link:'
        value: 'https://google.com'