apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook2
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - merge:
      mergeKeys:
        - path.basename
      generators:
        - git:
            repoURL: 'git@github.com:emelianrus/argocd_testing.git'
            revision: HEAD
            files:
              - path: apps/in-cluster/test/list-elementsYaml-example.yaml
        - list:
            elementsYaml: "{{ .components | toJson }}"  # Ensure .components exists in the list context
        - git:
            repoURL: https://github.com/argoproj/argo-cd.git
            revision: HEAD
            directories:
              - path: apps/in-cluster/*
  template:
    metadata:
      name: '{{.name}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: 'git@github.com:emelianrus/argocd_testing.git'
        path: apps/in-cluster/base-chart
        helm:
          valueFiles:
            - apps/in-cluster/{{.name}}/helm/values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: app