apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationroot
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: app1
spec:
  project: default
  source:
    path: apps/app1
    repoURL: 'https://github.com/emelianrus/argocd_testing.git'
    targetRevision: master
  destination:
    name: ''
    namespace: app
    server: 'https://kubernetes.default.svc'
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
